root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/saws ./cmd/saws"
  bin = "./tmp/saws"
  args_bin = ["up"]
  include_ext = ["go", "html", "js", "css", "yaml", "yml"]
  exclude_dir = ["tmp", ".saws", "vendor", "node_modules"]
  delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
